from src.domain.prompts.analyzer_prompts import ANALYZER_SYSTEM_PROMPT, ANALYZER_USER_PROMPT_TEMPLATE
from src.domain.prompts.extractor_prompts import EXTRACTOR_SYSTEM_PROMPT, EXTRACTOR_USER_PROMPT
from src.domain.prompts.judge_prompts import JUDGE_SYSTEM_PROMPT, JUDGE_USER_PROMPT_TEMPLATE

__all__ = [
    "EXTRACTOR_SYSTEM_PROMPT",
    "EXTRACTOR_USER_PROMPT",
    "ANALYZER_SYSTEM_PROMPT",
    "ANALYZER_USER_PROMPT_TEMPLATE",
    "JUDGE_SYSTEM_PROMPT",
    "JUDGE_USER_PROMPT_TEMPLATE",
]
